import { appTasks } from '@ohos/hvigor-ohos-plugin';
import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import path from 'node:path';

export default {
    system: appTasks,  /* Built-in plugin of Hvigor. It cannot be modified. */
    plugins:[]         /* Custom plugin to extend the functionality of Hvigor. */
}

// obsidian.asar is not committed to the repository (it is the official
// signed artifact with injected runtime patches, generated by
// scripts/update-obsidian.mjs). Make sure it exists BEFORE the build packs
// web_engine's resfile: a fresh clone generates it on first build, DevEco
// GUI and hvigorw alike. CI runs the explicit download+verify pipeline in
// build-release.yml with caching, so this is a fast no-op there.
// OHSIDIAN_SKIP_ASAR_ENSURE=1 disables the check.
// Fail-safe policy: when the asar cannot be produced we abort the build with
// instructions instead of silently packing a HAP without the app payload.
try {
    const root = process.cwd();
    const asarPath = path.join(root, 'web_engine', 'src', 'main', 'resources', 'resfile', 'resources', 'app', 'obsidian.asar');
    if (!existsSync(asarPath)) {
        const ensureScript = path.join(root, 'scripts', 'ensure-obsidian-asar.mjs');
        if (!existsSync(ensureScript)) {
            throw new Error('obsidian.asar is missing; run "npm ci --prefix scripts && node scripts/update-obsidian.mjs --repatch" from the project root first');
        }
        console.log('[OHsidian] obsidian.asar missing - generating it (official download, one-time)...');
        execFileSync(process.execPath, [ensureScript], { stdio: 'inherit', cwd: root });
    }
} catch (e) {
    console.error('[OHsidian] ' + (e && e.message ? e.message : String(e)));
    throw e;
}
